"""fix_timestamp

Revision ID: 5f70a1ebe4eb
Revises: fd9352f3a55e
Create Date: 2026-01-25 23:18:59.880582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f70a1ebe4eb"
down_revision: Union[str, Sequence[str], None] = "fd9352f3a55e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "description",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    op.add_column("user_data", sa.Column("email", sa.String(length=100), nullable=True))
    op.add_column(
        "user_data",
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.alter_column(
        "user_data",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_user_data_email"), "user_data", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_data_email"), table_name="user_data")
    op.alter_column(
        "user_data",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_column("user_data", "is_superuser")
    op.drop_column("user_data", "email")
    op.alter_column(
        "logs",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
