"""drop 3 unused tables

Revision ID: 649bba5d15fd
Revises: 5f70a1ebe4eb
Create Date: 2026-03-28 08:48:50.930021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '649bba5d15fd'
down_revision: Union[str, Sequence[str], None] = '5f70a1ebe4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_data')
    op.drop_table('environment_data')
    op.drop_table('actuator_data')
    op.alter_column('user_data', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user_data', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_data', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_data', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('actuator_data',
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('pump_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('light_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('automation_status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('deviceid', 'timestamp', name=op.f('pk_actuator_data'))
    )
    op.create_table('environment_data',
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('temperature_atas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temperature_bawah', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity_atas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('humidity_bawah', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('light_intensity_atas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('light_intensity_bawah', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('temperature_avg', sa.DOUBLE_PRECISION(precision=53), sa.Computed('((temperature_atas + temperature_bawah) / (2.0)::double precision)', persisted=True), autoincrement=False, nullable=False),
    sa.Column('humidity_avg', sa.DOUBLE_PRECISION(precision=53), sa.Computed('((humidity_atas + humidity_bawah) / (2.0)::double precision)', persisted=True), autoincrement=False, nullable=False),
    sa.Column('light_intensity_avg', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((light_intensity_atas + light_intensity_bawah))::numeric / 2.0)', persisted=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('deviceid', 'timestamp', name=op.f('pk_environment_data'))
    )
    op.create_table('sensor_data',
    sa.Column('deviceid', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('moisture1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moisture2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moisture3', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moisture4', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moisture5', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moisture6', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('flowrate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('total_litres', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('distance_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ph', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('tds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('moisture_avg', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((((((moisture1 + moisture2) + moisture3) + moisture4) + moisture5) + moisture6))::numeric / 6.0)', persisted=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('deviceid', 'timestamp', name=op.f('pk_sensor_data'))
    )
    # ### end Alembic commands ###
