"""init tables

Revision ID: 9e7dcb87127f
Revises: 
Create Date: 2025-10-12 17:25:53.424803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7dcb87127f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pgmigrations')
    op.drop_index(op.f('actuator_data_timestamp_idx'), table_name='actuator_data')
    op.add_column('environment_data', sa.Column('light_intensity_atas', sa.Integer(), server_default='0', nullable=False))
    op.add_column('environment_data', sa.Column('light_intensity_bawah', sa.Integer(), server_default='0', nullable=False))
    op.add_column('environment_data', sa.Column('avg_light_intensity', sa.DOUBLE_PRECISION(), server_default='0.0', nullable=False))
    op.alter_column('environment_data', 'temperature_atas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('environment_data', 'temperature_bawah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('environment_data', 'humidity_atas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('environment_data', 'humidity_bawah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('environment_data', 'avg_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('environment_data', 'avg_humidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('environment_data_timestamp_idx'), table_name='environment_data')
    op.alter_column('sensor_data', 'moisture1',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture2',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture3',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture4',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture5',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture6',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'moistureavg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'flowrate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'total_litres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'distance_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'ph',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sensor_data', 'tds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('sensor_data_timestamp_idx'), table_name='sensor_data')
    op.add_column('user_data', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column(
        "user_data",
        "userid",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="userid::uuid",
    )
    op.create_index(op.f('ix_user_data_username'), 'user_data', ['username'], unique=True)
    op.drop_column('user_data', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_data_username'), table_name='user_data')
    op.alter_column('user_data', 'userid',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('user_data', 'created_at')
    op.create_index(op.f('sensor_data_timestamp_idx'), 'sensor_data', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('sensor_data', 'tds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'ph',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'distance_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'total_litres',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'flowrate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moistureavg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture6',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture5',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture4',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture3',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture2',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('sensor_data', 'moisture1',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index(op.f('environment_data_timestamp_idx'), 'environment_data', [sa.literal_column('timestamp DESC')], unique=False)
    op.alter_column('environment_data', 'avg_humidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('environment_data', 'avg_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('environment_data', 'humidity_bawah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('environment_data', 'humidity_atas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('environment_data', 'temperature_bawah',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('environment_data', 'temperature_atas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('environment_data', 'avg_light_intensity')
    op.drop_column('environment_data', 'light_intensity_bawah')
    op.drop_column('environment_data', 'light_intensity_atas')
    op.create_index(op.f('actuator_data_timestamp_idx'), 'actuator_data', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_table('pgmigrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('run_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pgmigrations_pkey'))
    )
    # ### end Alembic commands ###
