"""Alter table user

Revision ID: a11a457ed31c
Revises: 649bba5d15fd
Create Date: 2026-03-28 09:40:14.029607

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a11a457ed31c"
down_revision: Union[str, Sequence[str], None] = "649bba5d15fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_data", sa.Column("fullname", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "user_data", sa.Column("phone_number", sa.String(length=20), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_data", "phone_number")
    op.drop_column("user_data", "fullname")
    # ### end Alembic commands ###
