"""initial_tables

Revision ID: d131747a84b2
Revises:
Create Date: 2025-12-29 18:05:09.172209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d131747a84b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actuator_data",
        sa.Column("deviceid", sa.String(length=50), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("pump_status", sa.Integer(), nullable=False),
        sa.Column("light_status", sa.Integer(), nullable=False),
        sa.Column("automation_status", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("deviceid", "timestamp", name=op.f("pk_actuator_data")),
    )
    op.create_table(
        "environment_data",
        sa.Column("deviceid", sa.String(length=50), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("temperature_atas", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("temperature_bawah", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "avg_temperature",
            sa.DOUBLE_PRECISION(),
            sa.Computed(
                "((temperature_atas + temperature_bawah) / 2.0)", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("humidity_atas", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("humidity_bawah", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "avg_humidity",
            sa.DOUBLE_PRECISION(),
            sa.Computed("((humidity_atas + humidity_bawah) / 2.0)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "light_intensity_atas", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "light_intensity_bawah", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "avg_light_intensity",
            sa.DOUBLE_PRECISION(),
            sa.Computed(
                "((light_intensity_atas + light_intensity_bawah) / 2.0)", persisted=True
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "deviceid", "timestamp", name=op.f("pk_environment_data")
        ),
    )
    op.create_table(
        "hydroponic_data",
        sa.Column("dataid", sa.UUID(), nullable=False),
        sa.Column("moisture1", sa.Integer(), nullable=False),
        sa.Column("moisture2", sa.Integer(), nullable=False),
        sa.Column("moisture3", sa.Integer(), nullable=False),
        sa.Column("moisture4", sa.Integer(), nullable=False),
        sa.Column("moisture5", sa.Integer(), nullable=False),
        sa.Column("moisture6", sa.Integer(), nullable=False),
        sa.Column(
            "moistureavg",
            sa.DOUBLE_PRECISION(),
            sa.Computed(
                "(moisture1 + moisture2 + moisture3 + moisture4 + moisture5 + moisture6) / 6.0",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("flowrate", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_litres", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("distance_cm", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("ph", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("tds", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("temperature_atas", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("temperature_bawah", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "temperature_avg",
            sa.DOUBLE_PRECISION(),
            sa.Computed(
                "((temperature_atas + temperature_bawah) / 2.0)", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("humidity_atas", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("humidity_bawah", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column(
            "humidity_avg",
            sa.DOUBLE_PRECISION(),
            sa.Computed("((humidity_atas + humidity_bawah) / 2.0)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "light_intensity_atas", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "light_intensity_bawah", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "light_intensity_avg",
            sa.DOUBLE_PRECISION(),
            sa.Computed(
                "((light_intensity_atas + light_intensity_bawah) / 2.0)", persisted=True
            ),
            nullable=False,
        ),
        sa.Column("pump_status", sa.Boolean(), nullable=False),
        sa.Column("light_status", sa.Boolean(), nullable=False),
        sa.Column("automation_status", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("dataid", name=op.f("pk_hydroponic_data")),
    )
    op.create_table(
        "sensor_data",
        sa.Column("deviceid", sa.String(length=50), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("moisture1", sa.Integer(), nullable=False),
        sa.Column("moisture2", sa.Integer(), nullable=False),
        sa.Column("moisture3", sa.Integer(), nullable=False),
        sa.Column("moisture4", sa.Integer(), nullable=False),
        sa.Column("moisture5", sa.Integer(), nullable=False),
        sa.Column("moisture6", sa.Integer(), nullable=False),
        sa.Column(
            "moistureavg",
            sa.DOUBLE_PRECISION(),
            sa.Computed(
                "(moisture1 + moisture2 + moisture3 + moisture4 + moisture5 + moisture6) / 6.0",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("flowrate", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("total_litres", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("distance_cm", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("ph", sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column("tds", sa.DOUBLE_PRECISION(), nullable=False),
        sa.PrimaryKeyConstraint("deviceid", "timestamp", name=op.f("pk_sensor_data")),
    )
    op.create_table(
        "user_data",
        sa.Column("userid", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.Enum("admin", "user", name="user_roles"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("userid", name=op.f("pk_user_data")),
    )
    op.create_index(
        op.f("ix_user_data_username"), "user_data", ["username"], unique=True
    )
    op.create_table(
        "logs",
        sa.Column("logid", sa.UUID(), nullable=False),
        sa.Column("userid", sa.UUID(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["userid"],
            ["user_data.userid"],
            name=op.f("fk_logs_userid_user_data"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("logid", name=op.f("pk_logs")),
    )

    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;")

    op.execute(
        "SELECT create_hypertable('sensor_data', 'timestamp', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT create_hypertable('environment_data', 'timestamp', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT create_hypertable('actuator_data', 'timestamp', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT create_hypertable('hydroponic_data', 'dataid', if_not_exists => TRUE);"
    )

    op.execute(
        "ALTER TABLE sensor_data SET (timescaledb.compress, timescaledb.compress_orderby = 'timestamp DESC');"
    )
    op.execute(
        "ALTER TABLE environment_data SET (timescaledb.compress, timescaledb.compress_orderby = 'timestamp DESC');"
    )
    op.execute(
        "ALTER TABLE actuator_data SET (timescaledb.compress, timescaledb.compress_orderby = 'timestamp DESC');"
    )
    op.execute(
        "ALTER TABLE hydroponic_data SET (timescaledb.compress, timescaledb.compress_orderby = 'dataid DESC');"
    )

    op.execute(
        "SELECT add_compression_policy('sensor_data', compress_after => INTERVAL '7d', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT add_compression_policy('environment_data', compress_after => INTERVAL '7d', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT add_compression_policy('actuator_data', compress_after => INTERVAL '7d', if_not_exists => TRUE);"
    )
    op.execute(
        "SELECT add_compression_policy('hydroponic_data', compress_after => INTERVAL '7d', if_not_exists => TRUE);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs", if_exists=True)
    op.drop_index(op.f("ix_user_data_username"), table_name="user_data")
    op.drop_table("user_data", if_exists=True)
    op.drop_table("sensor_data", if_exists=True)
    op.drop_table("hydroponic_data", if_exists=True)
    op.drop_table("environment_data", if_exists=True)
    op.drop_table("actuator_data", if_exists=True)
    user_roles = sa.Enum(name="user_roles")
    user_roles.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
