"""alter_avg_columns_name

Revision ID: fd9352f3a55e
Revises: d131747a84b2
Create Date: 2025-12-29 20:33:05.996377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd9352f3a55e'
down_revision: Union[str, Sequence[str], None] = 'd131747a84b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('actuator_data_timestamp_idx'), table_name='actuator_data')
    # op.drop_index(op.f('environment_data_timestamp_idx'), table_name='environment_data')
    # op.drop_index(op.f('sensor_data_timestamp_idx'), table_name='sensor_data')

    op.execute("ALTER TABLE environment_data SET (timescaledb.compress = false)")
    op.execute("ALTER TABLE hydroponic_data SET (timescaledb.compress = false)")
    op.execute("ALTER TABLE sensor_data SET (timescaledb.compress = false)")

    op.add_column('environment_data', sa.Column('temperature_avg', sa.DOUBLE_PRECISION(), sa.Computed('((temperature_atas + temperature_bawah) / 2.0)', persisted=True), nullable=False))
    op.add_column('environment_data', sa.Column('humidity_avg', sa.DOUBLE_PRECISION(), sa.Computed('((humidity_atas + humidity_bawah) / 2.0)', persisted=True), nullable=False))
    op.add_column('environment_data', sa.Column('light_intensity_avg', sa.DOUBLE_PRECISION(), sa.Computed('((light_intensity_atas + light_intensity_bawah) / 2.0)', persisted=True), nullable=False))
    op.drop_column('environment_data', 'avg_humidity')
    op.drop_column('environment_data', 'avg_light_intensity')
    op.drop_column('environment_data', 'avg_temperature')
    op.add_column('hydroponic_data', sa.Column('moisture_avg', sa.DOUBLE_PRECISION(), sa.Computed('((moisture1 + moisture2 + moisture3 + moisture4 + moisture5 + moisture6) / 6.0)', persisted=True), nullable=False))
    op.drop_column('hydroponic_data', 'moistureavg')
    op.add_column('sensor_data', sa.Column('moisture_avg', sa.DOUBLE_PRECISION(), sa.Computed('((moisture1 + moisture2 + moisture3 + moisture4 + moisture5 + moisture6) / 6.0)', persisted=True), nullable=False))
    op.drop_column('sensor_data', 'moistureavg')

    op.execute(
        "ALTER TABLE environment_data SET (timescaledb.compress, timescaledb.compress_orderby = 'timestamp DESC')"
    )
    op.execute(
        "ALTER TABLE hydroponic_data SET (timescaledb.compress, timescaledb.compress_orderby = 'dataid DESC')"
    )
    op.execute(
        "ALTER TABLE sensor_data SET (timescaledb.compress, timescaledb.compress_orderby = 'timestamp DESC')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_data', sa.Column('moistureavg', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((((((moisture1 + moisture2) + moisture3) + moisture4) + moisture5) + moisture6))::numeric / 6.0)', persisted=True), autoincrement=False, nullable=False))
    op.drop_column('sensor_data', 'moisture_avg')
    op.add_column('hydroponic_data', sa.Column('moistureavg', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((((((moisture1 + moisture2) + moisture3) + moisture4) + moisture5) + moisture6))::numeric / 6.0)', persisted=True), autoincrement=False, nullable=False))
   #  op.drop_column('hydroponic_data', 'moisture_avg')
   #  op.add_column('environment_data', sa.Column('avg_temperature', sa.DOUBLE_PRECISION(precision=53), sa.Computed('((temperature_atas + temperature_bawah) / (2.0)::double precision)', persisted=True), autoincrement=False, nullable=False))
   #  op.add_column('environment_data', sa.Column('avg_light_intensity', sa.DOUBLE_PRECISION(precision=53), sa.Computed('(((light_intensity_atas + light_intensity_bawah))::numeric / 2.0)', persisted=True), autoincrement=False, nullable=False))
    op.add_column('environment_data', sa.Column('avg_humidity', sa.DOUBLE_PRECISION(precision=53), sa.Computed('((humidity_atas + humidity_bawah) / (2.0)::double precision)', persisted=True), autoincrement=False, nullable=False))
    op.drop_column('environment_data', 'light_intensity_avg')
    op.drop_column('environment_data', 'humidity_avg')
    op.drop_column('environment_data', 'temperature_avg')
    # op.create_index(op.f('environment_data_timestamp_idx'), 'environment_data', [sa.literal_column('timestamp DESC')], unique=False)
    # op.create_index(op.f('sensor_data_timestamp_idx'), 'sensor_data', [sa.literal_column('timestamp DESC')], unique=False)
    # op.create_index(op.f('actuator_data_timestamp_idx'), 'actuator_data', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
